### ISSUE TITLE
Error al instalar FRIDA [BUG][Excel/Browpet/Titanium]

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#184]
**Describe the bug**
el usuario jmontalvo@hebmex.com al querer abrir FRIDA le aparece el siguiente mensaje
![image](https://user-images.githubusercontent.com/54727278/151911939-c15cb5b8-5acc-4f09-9647-ea4a39c54f04.png)

se descargó de cognitive testing el frida installer y aún después de reiniciar la máquina le aparece este mensaje
![image](https://user-images.githubusercontent.com/54727278/151911891-e1cd5f6e-afdc-4382-bf40-108a7a7a73dd.png)

a que podría deberse?
**To Reproduce**
Tu script o instruccioens que tienen la falla

**Bug information**
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

**Expected behavior**
Abrir EVA

**Screenshots**
Screenshots o video del problema

**Desktop (please complete the following information):**
no puedo ver su versión ya que no abre FRIDA

**Additional context**
Máquina física

**Comment by RickProductivity** [comment]
Oye tienes acceso al frida tester ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: heber-solis ***@***.***>
Sent: Monday, January 31, 2022 10:16:26 PM
To: FridaSupport/CognitiveTestingMX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FridaSupport/CognitiveTestingMX] Error al instalar EVA [BUG][Excel/Browpet/Titanium] (Issue #184)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Describe the bug
el usuario ***@***.******@***.***> al querer abrir FRIDA le aparece el siguiente mensaje
[image]<https://user-images.githubusercontent.com/54727278/151911939-c15cb5b8-5acc-4f09-9647-ea4a39c54f04.png>

se descargó de cognitive testing el frida installer y aún después de reiniciar la máquina le aparece este mensaje
[image]<https://user-images.githubusercontent.com/54727278/151911891-e1cd5f6e-afdc-4382-bf40-108a7a7a73dd.png>

a que podría deberse?
To Reproduce
Tu script o instruccioens que tienen la falla

Bug information
Informacion sobre las circunstancias en las que se presenta el bug (ID del proceso, usuario de Turing, log de ejecucion, mensaje de error, etc.)

Expected behavior
Abrir EVA

Screenshots
Screenshots o video del problema

Desktop (please complete the following information):
no puedo ver su versión ya que no abre FRIDA

Additional context
Máquina física

**Comment by heber-solis** [comment]
si, se corrió la prueba de la 1 a la 5 y marcó todo bien

**Comment by gantonioid** [comment]
Lo más frecuente es que ya esté Turing abierto (no visible)

Puedes verlo en task manager y cerrar aquellos que estén abiertos

**Comment by heber-solis** [comment]
si lo checamos, pero no aparece, por lo mismo se reinició la máquina para evitar cualquier tema como ese y persiste el error

**Comment by andresCruzF** [comment]
Hola @heber-solis ,

En complemento a las pruebas 1 y 5 de Turing Connection Tester podrias ejecutar la pruebas 2 y 3?

Saludos, quedo al pendiente

[Turing_Connection_Tester.zip](https://github.com/FridaSupport/CognitiveTestingMX/files/7980502/Turing_Connection_Tester.zip)

**Comment by heber-solis** [comment]
hola Andrés, si o sea se realizaron las pruebas 1,2,3,4,5 y marcó todo ok

**Comment by heber-solis** [comment]
![image](https://user-images.githubusercontent.com/54727278/152030094-ea58537d-034f-4574-9e90-3a11d17a839e.png)
este es el resultado de las pruebas

**Comment by andresCruzF** [comment]
@heber-solis, podrias volver a intentar ? Ya se genero un update a PUMBA para que este nos indique cuando alguno de los dlls o exe estan siendo ocupado al momento de realizar la secuencia de update 

![image](https://user-images.githubusercontent.com/49708627/152061726-ac2ef5f4-5302-4573-8771-05670d3829f0.png)

**Comment by heber-solis** [comment]
me comentó el usuario que ya pudo acceder, no se hizo nada adicional, solamente intentó después de un tiempo y ya lo dejó abrir FRIDA. pero esa update me va a servir mucho por que hay veces que a mi también me pasa esto jaja muchas gracias!
