### ISSUE TITLE
GetCurrentDate hour&minutes la hora desplegada es incorrecta

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#26]
La hora desplegada es incorrecta, por ejemplo muestra 9:8 en lugar de 09:08

**Comment by gantonioid** [comment]
Ese es el "Expected behaviour" retornar un string para que te encargues de parsearlo haciendo split por ':'

La misma instrucción tiene una variante de sintaxis que te acepta el formato deseado, aquí la línea que realmente quieres
GetCurrentDate Date{HH:mm es} and save as Date

Revisa [http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/GetCurrentDate](http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/GetCurrentDate)
en varias funciones tenemos sintaxis diferentes para atender las necesidades

**Comment by heber-solis** [comment]
GetCurrentDate Date{HH:mm es} and save as Date no aparece en ese apartado es por eso que teníamos la duda, muchas gracias

**Comment by gantonioid** [comment]
Aparece como `GetCurrentDate Date{<Format> <Language>} and save as <Date>`

ahí el "Format" se refiere a los [Formatos de fecha estándar](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings?view=netframework-4.8)
