### ISSUE TITLE
por que sucede error :context was destroyed?

### ISSUE THREAD

**Issue by heber-solis** [FridaSupport/CognitiveTestingMX#47]
[log.txt](https://github.com/FridaSupport/CognitiveTestingMX/files/4440094/log.txt)
me sucede este error:"Execution context was destroyed, most likely because of a navigation." muy seguido a pesar de que no se tiene ningún navigation y al parecer es random adjunto log de la ejecución

**Comment by gantonioid** [comment]
Hay documentación abundante de por qué sucede, y como el error lo menciona, lo más seguro es que haya una "navegación", es decir, un cambio de página (refresh, GoTo, click que genera una redirección, etc) que invalida el DOM con el que estás trabajando. Por eso el "contexto" de la instrucción se pierde.

Podría arreglarse con Web2 Navigation o Sleeps, hay que asegurarnos de no estar haciendo clicks sobre páginas que ya no existen, o que aún no cargan por completo.

Adjunto alguna documentación (técnica, pero explican lo que mencioné arriba)

- [https://github.com/puppeteer/puppeteer/issues/5056](https://github.com/puppeteer/puppeteer/issues/5056)
- [https://stackoverflow.com/questions/55877263/puppeteer-execution-context-was-destroyed-most-likely-because-of-a-navigation](https://stackoverflow.com/questions/55877263/puppeteer-execution-context-was-destroyed-most-likely-because-of-a-navigation)
